dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

script:
 - echo 5
